from sqlalchemy.orm import declarative_base

Base = declarative_base()


class CRUDMixin:
    """Small convenience mixin providing basic create/read/delete helpers
    used across the CLI and seed scripts.
    """
    @classmethod
    def create(cls, session, **kwargs):
        obj = cls(**kwargs)
        session.add(obj)
        # flush to populate autogenerated ids before returning
        session.flush()
        return obj

    @classmethod
    def get_all(cls, session):
        return session.query(cls).all()

    @classmethod
    def find_by_id(cls, session, id_):
        # prefer session.get when available (SQLAlchemy 1.4+)
        if hasattr(session, "get"):
            return session.get(cls, id_)
        return session.query(cls).get(id_)

    @classmethod
    def delete(cls, session, obj):
        session.delete(obj)


# Import submodules so that `from models import User` works at package level
from .user import User  # noqa: E402
from .movie import Movie  # noqa: E402
from .review import Review  # noqa: E402
from .genre import Genre  # noqa: E402

__all__ = ["Base", "CRUDMixin", "User", "Movie", "Review", "Genre"]
